import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

import SearchBar from "@/components/SearchBar";

import { FiGithub } from "react-icons/fi";

export default function Home() {
  return (
    <>
      <Head>
        <title>Find a Github user</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-50 min-h-screen">
        <div className="flex items-center justify-around w-[90%] lg:w-[750px] mx-auto pt-12">
          <FiGithub className="text-4xl font-bold" />
          <h1 className="text-center text-3xl font-bold">
            Find a Github user and list all their repositories
          </h1>
        </div>
        <SearchBar />
      </main>
    </>
  );
}
